import { useState, useMemo } from "react";
import { Link } from "wouter";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, Music, Trash2, Download, ExternalLink, Play, Shuffle } from "lucide-react";
import CollectionPlayer from "@/components/CollectionPlayer";
import { genres, getAllLikedTracks, unlikeTrack } from "@/data";
import type { Track } from "@/data";

const genreColors: Record<string, string> = {
  techno: '#00d4aa',
  afrobeats: '#ff6b6b',
  reggae: '#ffa726',
  reggaeton: '#e040fb',
  hiphop: '#ffb300',
  infantil: '#ff69b4',
};

const genreKeys = ['techno', 'afrobeats', 'reggae', 'reggaeton', 'hiphop', 'infantil'] as const;
type GenreFilter = 'all' | typeof genreKeys[number];

function exportPlaylist(tracks: Track[]) {
  const lines = [
    '# My Waveform Playlist',
    `# Exported on ${new Date().toLocaleDateString()}`,
    '',
    ...tracks.map((t, i) => {
      const genre = genres.find(g => g.key === t.genre);
      const attrs = t.attributes ? (typeof t.attributes === 'string' ? JSON.parse(t.attributes) : t.attributes) : { bpm: '?' };
      return `${i + 1}. ${t.artist} - ${t.title} [${genre?.name || t.genre}] (${attrs.bpm} BPM)`;
    }),
    '',
    '---',
    'Generated by Waveform Music Discovery',
  ];
  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'waveform-playlist.txt';
  a.click();
  URL.revokeObjectURL(url);
}

export default function Playlist() {
  const [likedTracks, setLikedTracks] = useState(() => getAllLikedTracks());
  const [filter, setFilter] = useState<GenreFilter>('all');
  const [showPlayer, setShowPlayer] = useState(false);

  const handleRemove = (track: Track) => {
    unlikeTrack(track.genre, track.id);
    setLikedTracks(getAllLikedTracks());
  };

  const filteredTracks = useMemo(() => {
    if (filter === 'all') return likedTracks;
    return likedTracks.filter(t => t.genre === filter);
  }, [likedTracks, filter]);

  const genreCounts = Object.fromEntries(
    genreKeys.map(g => [g, likedTracks.filter(t => t.genre === g).length])
  ) as Record<typeof genreKeys[number], number>;

  return (
    <div className="min-h-screen flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-20 glass-card border-b border-white/5">
        <div className="flex items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2 text-[oklch(0.6_0.01_260)] hover:text-[oklch(0.95_0.005_260)] transition-colors">
            <ArrowLeft className="w-5 h-5" />
            <span className="text-sm">Back</span>
          </Link>

          <h1 className="text-lg font-semibold">My Playlist</h1>

          <div className="flex items-center gap-2">
            {likedTracks.length > 0 && (
              <>
                <button
                  onClick={() => setShowPlayer(true)}
                  className="p-2 rounded-full hover:bg-white/5 transition-colors"
                  title="Shuffle play all"
                >
                  <Shuffle className="w-5 h-5 text-[#00d4aa]" />
                </button>
                <button
                  onClick={() => exportPlaylist(filteredTracks)}
                  className="p-2 rounded-full hover:bg-white/5 transition-colors"
                  title="Export playlist"
                >
                  <Download className="w-5 h-5 text-[oklch(0.6_0.01_260)]" />
                </button>
              </>
            )}
          </div>
        </div>

        {/* Filter tabs */}
        <div className="flex gap-2 px-6 pb-4 overflow-x-auto">
          <button
            onClick={() => setFilter('all')}
            className={`px-4 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-colors ${
              filter === 'all' ? 'bg-white/10 text-[oklch(0.95_0.005_260)]' : 'text-[oklch(0.6_0.01_260)] hover:text-[oklch(0.95_0.005_260)]'
            }`}
          >
            All ({likedTracks.length})
          </button>
          {genreKeys.map(g => {
            const genreInfo = genres.find(genre => genre.key === g);
            const color = genreColors[g] || '#888';
            return (
              <button
                key={g}
                onClick={() => setFilter(g)}
                className={`px-4 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-colors ${
                  filter === g ? '' : 'text-[oklch(0.6_0.01_260)] hover:text-[oklch(0.95_0.005_260)]'
                }`}
                style={filter === g ? { backgroundColor: `${color}20`, color } : {}}
              >
                {genreInfo?.name.split(' ')[0] || g} ({genreCounts[g]})
              </button>
            );
          })}
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 px-6 py-6">
        {likedTracks.length === 0 ? (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col items-center justify-center min-h-[50vh] text-center"
          >
            <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center mb-4">
              <Music className="w-8 h-8 text-[oklch(0.6_0.01_260)]" />
            </div>
            <h2 className="text-xl font-semibold mb-2">No tracks yet</h2>
            <p className="text-[oklch(0.6_0.01_260)] mb-6 max-w-sm">
              Start discovering music by exploring genres. Your liked songs will appear here.
            </p>
            <Link href="/" className="px-6 py-3 rounded-full bg-[#00d4aa] text-[#0d0d0d] font-medium text-sm">
              Start Discovering
            </Link>
          </motion.div>
        ) : (
          <div className="space-y-3">
            <AnimatePresence>
              {filteredTracks.map((track, index) => {
                const color = genreColors[track.genre] || '#888';
                const attrs = track.attributes ? (typeof track.attributes === 'string' ? JSON.parse(track.attributes) : track.attributes) : { bpm: 120 };
                return (
                  <motion.div
                    key={track.id}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, x: -100 }}
                    transition={{ delay: Math.min(index * 0.02, 0.5) }}
                    className="glass-card rounded-xl p-4 flex items-center gap-4 group"
                  >
                    {/* Play indicator */}
                    {track.youtubeId ? (
                      <a
                        href={`https://www.youtube.com/watch?v=${track.youtubeId}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0 transition-transform hover:scale-105"
                        style={{ backgroundColor: `${color}15` }}
                      >
                        <Play className="w-5 h-5" style={{ color }} />
                      </a>
                    ) : (
                      <div className="w-12 h-12 rounded-lg flex items-center justify-center flex-shrink-0" style={{ backgroundColor: `${color}15` }}>
                        <Play className="w-5 h-5 opacity-30" style={{ color }} />
                      </div>
                    )}

                    {/* Track info */}
                    <div className="flex-1 min-w-0">
                      <h3 className="font-medium text-sm truncate">{track.title}</h3>
                      <p className="text-xs text-[oklch(0.6_0.01_260)] truncate">{track.artist}</p>
                      <div className="flex items-center gap-2 mt-1">
                        <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: color }} />
                        <span className="text-[10px] text-[oklch(0.6_0.01_260)]">{attrs.bpm} BPM</span>
                        {track.label && <span className="text-[10px] text-[oklch(0.6_0.01_260)]">· {track.label}</span>}
                      </div>
                    </div>

                    {/* Actions */}
                    <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      {track.youtubeId && (
                        <a
                          href={`https://www.youtube.com/watch?v=${track.youtubeId}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="p-2 rounded-full hover:bg-white/10 transition-colors"
                        >
                          <ExternalLink className="w-4 h-4 text-[oklch(0.6_0.01_260)]" />
                        </a>
                      )}
                      <button
                        onClick={() => handleRemove(track)}
                        className="p-2 rounded-full hover:bg-red-400/10 transition-colors"
                      >
                        <Trash2 className="w-4 h-4 text-red-400" />
                      </button>
                    </div>
                  </motion.div>
                );
              })}
            </AnimatePresence>
          </div>
        )}
      </main>

      {/* Collection Player Overlay */}
      <AnimatePresence>
        {showPlayer && filteredTracks.length > 0 && (
          <CollectionPlayer
            tracks={filteredTracks}
            genreColor={filter !== 'all' ? genreColors[filter] : '#00d4aa'}
            onClose={() => setShowPlayer(false)}
            onRemove={(trackId) => {
              const track = likedTracks.find(t => t.id === trackId);
              if (track) handleRemove(track);
            }}
          />
        )}
      </AnimatePresence>
    </div>
  );
}
